/*
 * Ejemplo desarrollado por Erick Navarro
 * Blog: e-navarro.blogspot.com
 * Noviembre - 2015
 */

package chatservidor;

import java.awt.GridLayout;
import java.awt.PopupMenu;
import java.awt.SystemTray;
import java.awt.TrayIcon;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.UIManager;

/**
 * Clase que gestiona la interfaz gráfica del servidor, que muestra un log de 
 * las conexiones y desconexiones de los diferentes clientes, así como un mensaje
 * de confirmación de que el servidor esta corriendo correctamente.
 * @author Erick Navarro
 */
public class VentanaS extends javax.swing.JFrame {
    private final String DEFAULT_PORT="5000";
    private final Servidor servidor;
    private ImageIcon imageIcon;
    private TrayIcon trayIcon;
    private SystemTray systemTrayServer;
    
    /**
     * Creates new form Ventana
     */
    public VentanaS() {
        imageIcon = new ImageIcon(this.getClass().getResource("/icons/server-64.png"));
        initComponents();
        this.setIconImage(imageIcon.getImage());
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        String puerto=getPuerto();
        servidor=new Servidor(puerto, this);
        initSystemTray();
    }

    private void initSystemTray() {
        trayIcon = new TrayIcon(imageIcon.getImage(), "Servidor de SIGCO", ppmOpcionesServidor);
        trayIcon.setImageAutoSize(true);
        systemTrayServer = SystemTray.getSystemTray();
    }   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ppmOpcionesServidor = new java.awt.PopupMenu();
        mitMostrar = new java.awt.MenuItem();
        mitCerrarServidor = new java.awt.MenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtClientes = new javax.swing.JTextArea();

        ppmOpcionesServidor.setLabel("popupMenu1");

        mitMostrar.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        mitMostrar.setLabel("Mostrar");
        mitMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitMostrarActionPerformed(evt);
            }
        });
        ppmOpcionesServidor.add(mitMostrar);

        mitCerrarServidor.setLabel("Cerrar Servidor");
        mitCerrarServidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitCerrarServidorActionPerformed(evt);
            }
        });
        ppmOpcionesServidor.add(mitCerrarServidor);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Servidor");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Log del Servidor"));

        txtClientes.setEditable(false);
        txtClientes.setColumns(20);
        txtClientes.setRows(5);
        jScrollPane1.setViewportView(txtClientes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            if (SystemTray.isSupported()){
                systemTrayServer.add(trayIcon);
                this.setVisible(false);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_formWindowClosing

    private void mitMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitMostrarActionPerformed
        systemTrayServer.remove(trayIcon);
        this.setVisible(true);
    }//GEN-LAST:event_mitMostrarActionPerformed

    private void mitCerrarServidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitCerrarServidorActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mitCerrarServidorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (Exception e) {
                    e.printStackTrace();
                }
                new VentanaS().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.MenuItem mitCerrarServidor;
    private java.awt.MenuItem mitMostrar;
    private java.awt.PopupMenu ppmOpcionesServidor;
    private javax.swing.JTextArea txtClientes;
    // End of variables declaration//GEN-END:variables
    /**
     * Método que agrega una línea de texto al log.
     * @param texto 
     */
    void agregarLog(String texto) {
        txtClientes.append(texto);
    }
    /**
     * Método que abre una ventana para que el usuario ingrese el puerto que 
     * desea utilizar para que el servidor escuche.
     * @return 
     */
    private String getPuerto() {
        String p=DEFAULT_PORT;
        JTextField puerto = new JTextField(20);
        puerto.setText(p);
        JPanel myPanel = new JPanel();
        myPanel.setLayout(new GridLayout(2, 1));
        myPanel.add(new JLabel("Puerto de la conexión:"));
        myPanel.add(puerto);
        int result = JOptionPane.showConfirmDialog(null, myPanel, 
                 "Configuraciones de la comunicación", JOptionPane.OK_CANCEL_OPTION);
        if (result == JOptionPane.OK_OPTION) {
                p=puerto.getText();
        }else{
            System.exit(0);
        }
        return p;
    }
    /**
     * Método que agrega un mensaje de confirmación al log cuando el servidor está
     * corriendo correctamente.
     */
    void addServidorIniciado() {
        txtClientes.setText("Inicializando el servidor... [Ok].");
    }        
}
